name: directus-extensions

include:
  - path: docker/compose.yaml

services:
  database:
    volumes:
      - ./.data/database:/var/lib/postgresql

  cache:
    volumes:
      - ./.data/cache:/data

  directus:
    ports:
      - '8055:8055'
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
      garage-init:
        condition: service_completed_successfully
      mailpit:
        condition: service_started
      meilisearch:
        condition: service_started
    volumes:
      - ./.data/uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./configuration:/directus/configuration
      - ./extensions/directus-configuration-poc:/directus/configuration/node_modules/@onderwijsin/directus-configuration-poc:ro
      - ./extensions/directus-magic-links-bundle/templates:/directus/templates:ro
    environment:
      CONFIGURATION_PATH: /directus/configuration/config.ts
      POC_SECRET: ${POC_SECRET:-local-poc-secret}

  mailpit:
    ports:
      - '8025:8025'
    volumes:
      - ./.data/mailpit:/data

  garage:
    volumes:
      - ./.data/garage/meta:/var/lib/garage/meta
      - ./.data/garage/data:/var/lib/garage/data

  garage-init:
    volumes:
      - ./.data/garage/meta:/var/lib/garage/meta:ro
      - ./docker/garage-init.sh:/usr/local/bin/garage-init.sh:ro

  meilisearch:
    ports:
      - '7700:7700'
    volumes:
      - ./.data/meilisearch:/meili_data
