services:
    database:
        image: postgis/postgis:15-master
        # Required when running on platform other than amd64, like Apple M1/M2:
        platform: linux/amd64
        volumes:
        - ./.local/database/postgres-15:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: directus
            POSTGRES_USER: directus
            POSTGRES_PASSWORD: directus

    cache:
        image: redis:6

    directus:
        image: directus/directus:11.4.1
        ports:
            - 8055:8055
        volumes:
            - ./.local/uploads:/directus/uploads
            - ./packages:/directus/extensions/
        depends_on:
            - cache
            - database
        environment:
            PUBLIC_URL: "http://localhost:8055"
            SECRET: "replace-with-random-value"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "admin"

            # DB auth is handled in .env
            DB_CLIENT: "pg"
            DB_HOST: "database"
            DB_PORT: 5432
            DB_DATABASE: "directus"
            DB_USER: "directus"
            DB_PASSWORD: "directus"

            CACHE_ENABLED: true
            CACHE_STORE: "redis"
            CACHE_TTL: "10m"

            REDIS: "redis://cache:6379"

            EXTENSIONS_AUTO_RELOAD: true
            WEBSOCKETS_ENABLED: true
            GRAPHQL_INTROSPECTION: true
            GRAPHQL_PLAYGROUND: true
            SESSION_COOKIE_SECURE: true 
            REFRESH_TOKEN_COOKIE_SECURE: true
