# Define common configurations as extension fields (YAML anchors)
x-directus-common: &directus-common
  env_file:
    - .env
  image: directus/directus:11.4.1
  volumes:
    - ./.local/uploads:/directus/uploads
    - ./packages:/directus/extensions/
  networks:
    - directus-net

x-directus-env: &directus-env
  SECRET: "replace-with-random-value"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "admin"
  DB_CLIENT: "pg"
  DB_PORT: 5432
  DB_USER: "directus"
  DB_PASSWORD: "directus"
  EXTENSIONS_AUTO_RELOAD: true
  WEBSOCKETS_ENABLED: true

x-db-common: &db-common
  image: postgres:16.6
  # Required when running on platform other than amd64, like Apple M1/M2:
  platform: linux/amd64
  networks:
    - directus-net
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U directus -d $${POSTGRES_DB}"]
    interval: 3s
    timeout: 5s
    retries: 5

x-db-env: &db-env
  POSTGRES_USER: directus
  POSTGRES_PASSWORD: directus

services:
  # Directus instances
  directus1:
    <<: *directus-common
    ports:
      - 8055:8055
    depends_on:
      database1:
        condition: service_healthy
    environment:
      <<: *directus-env
      PUBLIC_URL: "http://localhost:8055"
      DB_HOST: "database1"
      DB_DATABASE: "directus1"
      SESSION_COOKIE_NAME: "directus1_session_token"

  directus2:
    <<: *directus-common
    ports:
      - 8056:8055
    depends_on:
      database2:
        condition: service_healthy
    environment:
      <<: *directus-env
      PUBLIC_URL: "http://localhost:8056"
      DB_HOST: "database2"
      DB_DATABASE: "directus2"
      SESSION_COOKIE_NAME: "directus2_session_token"

  directus3:
    <<: *directus-common
    ports:
      - 8057:8055
    depends_on:
      database3:
        condition: service_healthy
    environment:
      <<: *directus-env
      PUBLIC_URL: "http://localhost:8057"
      DB_HOST: "database3"
      DB_DATABASE: "directus3"
      SESSION_COOKIE_NAME: "directus3_session_token"

  # Databases
  database1:
    <<: *db-common
    volumes:
      - ./.local/database/postgres-16-db1:/var/lib/postgresql/data
    environment:
      <<: *db-env
      POSTGRES_DB: directus1

  database2:
    <<: *db-common
    volumes:
      - ./.local/database/postgres-16-db2:/var/lib/postgresql/data
    environment:
      <<: *db-env
      POSTGRES_DB: directus2

  database3:
    <<: *db-common
    volumes:
      - ./.local/database/postgres-16-db3:/var/lib/postgresql/data
    environment:
      <<: *db-env
      POSTGRES_DB: directus3

networks:
  directus-net:
    driver: bridge