#!/usr/bin/env sh
. "$(dirname "$0")/h"

# Auto-capitalize commit subject
awk 'NR==1 { print toupper(substr($0,1,1)) substr($0,2) } NR!=1' "$1" > "$1.tmp" && mv "$1.tmp" "$1"

pnpm commitlint --edit "$1"
