/** A deliberately focused set of Shiki languages for web and general-purpose development. */
export const codeLanguageOptions = [
	{ text: 'Plain text', value: 'plaintext' },
	{ text: 'HTML', value: 'html' },
	{ text: 'CSS', value: 'css' },
	{ text: 'SCSS', value: 'scss' },
	{ text: 'Sass', value: 'sass' },
	{ text: 'Less', value: 'less' },
	{ text: 'Stylus', value: 'stylus' },
	{ text: 'PostCSS', value: 'postcss' },
	{ text: 'JavaScript', value: 'js' },
	{ text: 'TypeScript', value: 'ts' },
	{ text: 'JSX', value: 'jsx' },
	{ text: 'TSX', value: 'tsx' },
	{ text: 'Vue', value: 'vue' },
	{ text: 'Vue HTML', value: 'vue-html' },
	{ text: 'Svelte', value: 'svelte' },
	{ text: 'Astro', value: 'astro' },
	{ text: 'Angular HTML', value: 'angular-html' },
	{ text: 'Angular TypeScript', value: 'angular-ts' },
	{ text: 'Markdown', value: 'md' },
	{ text: 'MDX', value: 'mdx' },
	{ text: 'MDC', value: 'mdc' },
	{ text: 'GraphQL', value: 'graphql' },
	{ text: 'SQL', value: 'sql' },
	{ text: 'Prisma', value: 'prisma' },
	{ text: 'PHP', value: 'php' },
	{ text: 'Blade', value: 'blade' },
	{ text: 'Twig', value: 'twig' },
	{ text: 'Liquid', value: 'liquid' },
	{ text: 'Handlebars', value: 'hbs' },
	{ text: 'Pug', value: 'pug' },
	{ text: 'Python', value: 'python' },
	{ text: 'Ruby', value: 'ruby' },
	{ text: 'Java', value: 'java' },
	{ text: 'Kotlin', value: 'kotlin' },
	{ text: 'C', value: 'c' },
	{ text: 'C++', value: 'cpp' },
	{ text: 'C#', value: 'csharp' },
	{ text: 'Go', value: 'go' },
	{ text: 'Rust', value: 'rust' },
	{ text: 'Swift', value: 'swift' },
	{ text: 'Dart', value: 'dart' },
	{ text: 'Objective-C', value: 'objective-c' },
	{ text: 'Lua', value: 'lua' },
	{ text: 'R', value: 'r' },
	{ text: 'Elixir', value: 'elixir' },
	{ text: 'Erlang', value: 'erlang' },
	{ text: 'Shell / Bash', value: 'bash' },
	{ text: 'PowerShell', value: 'powershell' },
	{ text: 'Batch', value: 'batch' },
	{ text: 'JSON', value: 'json' },
	{ text: 'JSON with comments', value: 'jsonc' },
	{ text: 'JSON5', value: 'json5' },
	{ text: 'YAML', value: 'yaml' },
	{ text: 'TOML', value: 'toml' },
	{ text: 'XML', value: 'xml' },
	{ text: 'CSV', value: 'csv' },
	{ text: 'INI', value: 'ini' },
	{ text: 'Properties', value: 'properties' },
	{ text: '.env', value: 'dotenv' },
	{ text: 'HCL', value: 'hcl' },
	{ text: 'Terraform', value: 'terraform' },
	{ text: 'Dockerfile', value: 'dockerfile' },
	{ text: 'Nginx', value: 'nginx' },
	{ text: 'Apache', value: 'apache' },
	{ text: 'Makefile', value: 'makefile' },
	{ text: 'CMake', value: 'cmake' },
	{ text: 'Nix', value: 'nix' },
	{ text: 'Groovy / Gradle', value: 'groovy' },
]
