name: Changeset status

on:
  pull_request:
  merge_group:

permissions: {}

concurrency:
  group: changeset-status-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changeset_status:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      comment-body: ${{ steps.changesets.outputs.comment-body }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Generate Changeset status
        id: changesets
        uses: changesets/action/pr-status@72b60a2c449090fd1871c5578768a32a76011a9d # v2.1.0

  changeset_comment:
    needs: changeset_status
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment Changeset status
        uses: changesets/action/pr-comment@72b60a2c449090fd1871c5578768a32a76011a9d # v2.1.0
        with:
          body: ${{ needs.changeset_status.outputs.comment-body }}
