name: Refresh pnpm lockfile for Dependabot PRs

on:
  pull_request:
    branches:
      - "dependabot/**"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9  # Ensure this matches your pnpm version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pnpm-lock.yaml
          git commit -m "fix(deps): Regenerate lockfile" || echo "No changes to commit"
          git push